### ISSUE TITLE
Missing parameter 'recommendedConfig' in FlatCompat constructor.

### ISSUE THREAD

**Issue by fudom** [eslint/eslintrc#163]
From eslint v8 to v9 the config has been changed. We use the eslintrc config compat since we cannot migrate.
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config

**eslint.config.mjs**

```js
import { FlatCompat } from "@eslint/eslintrc";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

export default [...compat.extends("./.eslintrc.json")];
```

**Error**

```plaintext
TypeError: Missing parameter 'recommendedConfig' in FlatCompat constructor.

Referenced from: ./.eslintrc.json
    at getEslintRecommendedConfig (./node_modules/@eslint/eslintrc/lib/flat-compat.js:233:27)
    at ConfigArrayFactory._loadExtendedBuiltInConfig (./node_modules/@eslint/eslintrc/lib/config-array-factory.js:839:50)
    at ConfigArrayFactory._loadExtends (./node_modules/@eslint/eslintrc/lib/config-array-factory.js:805:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (./node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (./node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (./node_modules/@eslint/eslintrc/lib/config-array-factory.js:787:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (./node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
```

**Version (snippet)**

```json
{
  "devDependencies": {
    "@angular-eslint/builder": "^18.0.1",
    "@angular-eslint/eslint-plugin": "^18.0.1",
    "@angular-eslint/eslint-plugin-template": "^18.0.1",
    "@angular-eslint/schematics": "^18.0.1",
    "@angular-eslint/template-parser": "^18.0.1",
    "@eslint/eslintrc": "^3.1.0",
    "@typescript-eslint/eslint-plugin": "^7.11.0",
    "@typescript-eslint/parser": "^7.11.0",
    "eslint": "^9.4.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-only-warn": "^1.1.0",
    "typescript": "^5.4.5"
  }
}
```

**Comment by aladdin-add** [comment]
please read: https://github.com/eslint/eslintrc?tab=readme-ov-file#troubleshooting
