### ISSUE TITLE
"TypeError: Unexpected array" when importing @typescript-eslint

### ISSUE THREAD

**Issue by Rabadash8820** [eslint/eslintrc#97]
Hello, I can't tell if the issue I'm experiencing is user error, a bug in this package, or incompatibility in the 3rd party [@typescript-eslint](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) plugin. Basically I'm trying to use that plugin to add TypeScript linting rules, while using the new flat config file format.

Here is the folder structure for my repo (a game called "Farmageddon"):

- Root
  - backend/
    - eslint.config.js
    - tsconfig.json
    - package.json
    - src/
      - .ts files
    - test/
      - .ts files

And file contents:

<details>
    <summary>eslint.config.js</summary>

Inspired by:

  
- The [new config file format](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new) docs for ESLint
- The [Readme for this package](https://www.npmjs.com/package/@eslint/eslintrc)
- The `@typescript-eslint` docs on [Getting Started](https://typescript-eslint.io/docs/), [Typed Linting](https://typescript-eslint.io/docs/linting/typed-linting), and [Configuration](https://typescript-eslint.io/docs/linting/configs)

```js
import path from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

// Mimic CommonJS variables
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  // I've also tried every combination of commenting out these properties, but always get the same output
  baseDirectory: __dirname,
  resolvePluginsRelativeTo: __dirname,
});

export default [
  "eslint:recommended",
  compat.config({
    plugins: ["@typescript-eslint"],
    extends: [
      "plugin:@typescript-eslint/recommended",
      "plugin:@typescript-eslint/recommended-requiring-type-checking",
    ]
  }),
  {
    ignores: [
        // ...
    ],
  },
  {
    languageOptions: {
      // I've also tried using `import tsEslintParser from "@typescript-eslint/parser"` then passing `tsEslintParser` to this property, but same output
      parser: "@typescript-eslint/parser",
      ecmaVersion: "latest",
    },
  },
  {
    files: ["*.ts"],
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: __dirname,
        project: ["./tsconfig.json"],
      },
    },
    rules: {
      // ...
    }
  },
];
```

</details>

<details>
  <summary>tsconfig.json</summary>

Inspired by `tsc --init` and the [TS configuration docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "include": [
    "src/**/*.ts",
    "test/**/*.ts",
  ],
  "exclude": [
    "node_modules/"
  ],
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */
    "incremental": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "dist/",
    "composite": false,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
  }
}
```

</details>

<details>
  <summary>package.json</summary>

```json
{
  "name": "<my-package>",
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "compile": "tsc",
    "lint": "eslint --fix .",
  },
  "dependencies": {
    "source-map-support": "^0.5.20"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^1.3.3",
    "@tsconfig/node16": "^1.0.3",
    "@types/aws-lambda": "^8.10.84",
    "@types/node": "^16.11.0",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "esbuild": "^0.15.10",
    "eslint": "^8.0.1",
    "jest": "^29.1.2",
    "ts-jest": "^29.0.3",
    "ts-mockito": "^2.6.1",
    "typescript": "^4.4.4"
  }
}
```

</details>

When I run `npm run lint -- --debug`, I get a `TypeError: Unexpected array` error with the following debug logs:

<details>
    <summary>ESLint output</summary>

```log
eslint:cli CLI args: [ '--fix', '.', '--debug' ] +0ms
  eslint:cli Using flat config? true +8ms
  eslint:cli Running on files +6ms
  eslint:flat-eslint Searching for eslint.config.js +0ms
  eslint:flat-eslint Loading config from /workspaces/Farmageddon/backend/eslint.config.js +1ms
  eslint:flat-eslint Config file URL is file:///workspaces/Farmageddon/backend/eslint.config.js +0ms
  eslintrc:config-array-factory Loading {extends:"plugin:@typescript-eslint/recommended"} relative to  +0ms
  eslintrc:config-array-factory Loading plugin "@typescript-eslint" from  +1ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/eslint-plugin@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +1ms
  eslint:rules Loading rule 'brace-style' (remaining=287) +0ms
  eslint:rules Loading rule 'comma-dangle' (remaining=286) +11ms
  eslint:rules Loading rule 'dot-notation' (remaining=285) +12ms
  eslint:rules Loading rule 'indent' (remaining=284) +8ms
  eslint:rules Loading rule 'init-declarations' (remaining=283) +16ms
  eslint:rules Loading rule 'keyword-spacing' (remaining=282) +2ms
  eslint:rules Loading rule 'lines-between-class-members' (remaining=281) +2ms
  eslint:rules Loading rule 'no-dupe-class-members' (remaining=280) +27ms
  eslint:rules Loading rule 'no-duplicate-imports' (remaining=279) +3ms
  eslint:rules Loading rule 'no-empty-function' (remaining=278) +4ms
  eslint:rules Loading rule 'no-extra-parens' (remaining=277) +4ms
  eslint:rules Loading rule 'no-extra-semi' (remaining=276) +3ms
  eslint:rules Loading rule 'no-invalid-this' (remaining=275) +15ms
  eslint:rules Loading rule 'no-loop-func' (remaining=274) +2ms
  eslint:rules Loading rule 'no-loss-of-precision' (remaining=273) +1ms
  eslint:rules Loading rule 'no-magic-numbers' (remaining=272) +2ms
  eslint:rules Loading rule 'no-restricted-imports' (remaining=271) +37ms
  eslint:rules Loading rule 'no-unused-expressions' (remaining=270) +71ms
  eslint:rules Loading rule 'no-useless-constructor' (remaining=269) +6ms
  eslint:rules Loading rule 'object-curly-spacing' (remaining=268) +21ms
  eslint:rules Loading rule 'quotes' (remaining=267) +147ms
  eslint:rules Loading rule 'semi' (remaining=266) +52ms
  eslint:rules Loading rule 'space-before-blocks' (remaining=265) +7ms
  eslint:rules Loading rule 'space-infix-ops' (remaining=264) +4ms
  eslintrc:config-array-factory Plugin /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 1598ms +2s
  eslintrc:config-array-factory Loading {extends:"./configs/base"} relative to /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslintrc:config-array-factory package.json was not found: Cannot find module './configs/base/package.json'
Require stack:
- /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +1ms
  eslintrc:config-array-factory Loaded: ./configs/base (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js) +0ms
  eslintrc:config-array-factory Loading JS config file: /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js +1ms
  eslintrc:config-array-factory Loading parser "@typescript-eslint/parser" from /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js +2ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/parser@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/parser/dist/index.js) +0ms
  eslintrc:config-array-factory Loading plugin "@typescript-eslint" from /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js +2ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/eslint-plugin@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +1ms
  eslintrc:config-array-factory Plugin /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 0ms +0ms
  eslintrc:config-array-factory Loading {extends:"./configs/eslint-recommended"} relative to /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslintrc:config-array-factory package.json was not found: Cannot find module './configs/eslint-recommended/package.json'
Require stack:
- /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +1ms
  eslintrc:config-array-factory Loaded: ./configs/eslint-recommended (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js) +0ms
  eslintrc:config-array-factory Loading JS config file: /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js +0ms
  eslintrc:config-array-factory Loading {extends:"plugin:@typescript-eslint/recommended-requiring-type-checking"} relative to  +5ms
  eslintrc:config-array-factory Loading plugin "@typescript-eslint" from  +0ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/eslint-plugin@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +1ms
  eslintrc:config-array-factory Plugin /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 0ms +0ms
  eslintrc:config-array-factory Loading {extends:"./configs/base"} relative to /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslintrc:config-array-factory package.json was not found: Cannot find module './configs/base/package.json'
Require stack:
- /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslintrc:config-array-factory Loaded: ./configs/base (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js) +0ms
  eslintrc:config-array-factory Loading JS config file: /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js +0ms
  eslintrc:config-array-factory Loading parser "@typescript-eslint/parser" from /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js +1ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/parser@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/parser/dist/index.js) +0ms
  eslintrc:config-array-factory Loading plugin "@typescript-eslint" from /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/base.js +1ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/eslint-plugin@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +0ms
  eslintrc:config-array-factory Plugin /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 0ms +0ms
  eslintrc:config-array-factory Loading {extends:"./configs/eslint-recommended"} relative to /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslintrc:config-array-factory package.json was not found: Cannot find module './configs/eslint-recommended/package.json'
Require stack:
- /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js +0ms
  eslintrc:config-array-factory Loaded: ./configs/eslint-recommended (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js) +0ms
  eslintrc:config-array-factory Loading JS config file: /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js +0ms
  eslintrc:config-array-factory Loading plugin "@typescript-eslint" from  +2ms
  eslintrc:config-array-factory Loaded: @typescript-eslint/eslint-plugin@5.39.0 (/workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js) +1ms
  eslintrc:config-array-factory Plugin /workspaces/Farmageddon/backend/node_modules/@typescript-eslint/eslint-plugin/dist/index.js loaded in: 0ms +0ms
  eslintrc:flat-compat Resolving parser 'undefined' relative to /workspaces/Farmageddon/backend/__placeholder.js +0ms
  eslintrc:flat-compat Translating plugins: [object Object] +0ms
  eslintrc:flat-compat Translating plugin: @typescript-eslint +1ms
  eslintrc:flat-compat Resolving plugin '@typescript-eslint relative to /workspaces/Farmageddon/backend/__placeholder.js +0ms
  eslintrc:flat-compat Resolving parser 'undefined' relative to /workspaces/Farmageddon/backend/__placeholder.js +0ms
  eslintrc:flat-compat Translating plugins: [object Object] +0ms
  eslintrc:flat-compat Translating plugin: @typescript-eslint +0ms
  eslintrc:flat-compat Resolving plugin '@typescript-eslint relative to /workspaces/Farmageddon/backend/__placeholder.js +0ms
  eslintrc:flat-compat Translating plugins: [object Object] +0ms
  eslintrc:flat-compat Translating plugin: @typescript-eslint +1ms
  eslintrc:flat-compat Resolving plugin '@typescript-eslint relative to /workspaces/Farmageddon/backend/__placeholder.js +0ms

Oops! Something went wrong! :(

ESLint: 8.24.0

TypeError: Unexpected array.
    at flatTraverse (/workspaces/Farmageddon/backend/node_modules/@humanwhocodes/config-array/api.js:183:12)
    at flatTraverse.next (<anonymous>)
    at normalize (/workspaces/Farmageddon/backend/node_modules/@humanwhocodes/config-array/api.js:201:19)
    at async FlatConfigArray.normalize (/workspaces/Farmageddon/backend/node_modules/@humanwhocodes/config-array/api.js:603:30)
    at async calculateConfigArray (/workspaces/Farmageddon/backend/node_modules/eslint/lib/eslint/flat-eslint.js:443:5)
    at async FlatESLint.lintFiles (/workspaces/Farmageddon/backend/node_modules/eslint/lib/eslint/flat-eslint.js:776:25)
    at async Object.execute (/workspaces/Farmageddon/backend/node_modules/eslint/lib/cli.js:395:23)
    at async main (/workspaces/Farmageddon/backend/node_modules/eslint/bin/eslint.js:135:24)
```

</details

If this is not a bug, then some guidance would be much appreciated!

Note that I am running this command in a VS Code devcontainer with Node 16.18.1 and npm 8.19.2 installed, on WSL2 on Windows 11 Pro.

**Comment by nzakas** [comment]
This is actually an issue with [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) rather than ESLint itself. Please open an issue there.

**Comment by Rabadash8820** [comment]
Hi @nzakas, could you please elaborate? My understanding was that this package would allow me to import legacy ESLint plugins like `@typescript-eslint` into the newer flat config file format, but instead I am getting errors during import as shown in the above logs. To clarify, `TypeError: Unexpected array` is _not_ a linting error; linting isn't starting at all with my current setup.

**Comment by varunkumar** [comment]
Facing the same issue. Any solutions?

**Comment by varunkumar** [comment]
Figured out the issue. `compat.config` is returning an array and has to be used with a spread operator `...`. [README.md](../../README.md) has also been updated recently. @Rabadash8820
